/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        editorial: ['editorial'],
        'editorial-italic': ['editorial-italic'],
        montreal: ['montreal'],
      },
      colors: {
        charcoal: '#292A2D',
        parchment: '#DAD5CB',
        whisper: '#EEEFF0',
        eggshell: '#F5F4F0',
        ivory: '#FBFBF9',
        seafoam: '#A9D8C8',
        off: '#9B9B9B',
        'habit-purple': '#D9D9FF',
        'habit-green': '#E6FFD9',
        'habit-red': '#E5B2B2',
        'habit-orange': '#E5BFB2',
        'habit-yellow': '#E5CDB2',
        'habit-light-yellow': '#E5DAB2',
        'habit-lime': '#E3E5B2',
        'habit-light-lime': '#D5E5B2',
        'habit-mint': '#C8E5B2',
        'habit-light-mint': '#BBE5B2',
        'habit-teal': '#B2E5B6',
        'habit-light-teal': '#B2E5C4',
        'habit-cyan': '#B2E5D1',
        'habit-light-cyan': '#B2E5DE',
        'habit-sky': '#B2DEE5',
        'habit-light-sky': '#B2D1E5',
        'habit-blue': '#B2C4E5',
        'habit-light-blue': '#B2B6E5',
        'habit-indigo': '#BBB2E5',
        'habit-light-indigo': '#C8B2E5',
        'habit-violet': '#D5B2E5',
        'habit-light-violet': '#E3B2E5',
        'habit-pink': '#E5B2DA',
        'habit-light-pink': '#E5B2CD',
        'habit-rose': '#E5B2BF',
      },
    },
  },
  safelist: [
    'bg-habit-purple',
    'bg-habit-green',
    'bg-habit-red',
    'bg-habit-orange',
    'bg-habit-yellow',
    'bg-habit-light-yellow',
    'bg-habit-lime',
    'bg-habit-light-lime',
    'bg-habit-mint',
    'bg-habit-light-mint',
    'bg-habit-teal',
    'bg-habit-light-teal',
    'bg-habit-cyan',
    'bg-habit-light-cyan',
    'bg-habit-sky',
    'bg-habit-light-sky',
    'bg-habit-blue',
    'bg-habit-light-blue',
    'bg-habit-indigo',
    'bg-habit-light-indigo',
    'bg-habit-violet',
    'bg-habit-light-violet',
    'bg-habit-pink',
    'bg-habit-light-pink',
    'bg-habit-rose',
    'border-habit-purple',
    'border-habit-green',
    'border-habit-red',
    'border-habit-orange',
    'border-habit-yellow',
    'border-habit-light-yellow',
    'border-habit-lime',
    'border-habit-light-lime',
    'border-habit-mint',
    'border-habit-light-mint',
    'border-habit-teal',
    'border-habit-light-teal',
    'border-habit-cyan',
    'border-habit-light-cyan',
    'border-habit-sky',
    'border-habit-light-sky',
    'border-habit-blue',
    'border-habit-light-blue',
    'border-habit-indigo',
    'border-habit-light-indigo',
    'border-habit-violet',
    'border-habit-light-violet',
    'border-habit-pink',
    'border-habit-light-pink',
    'border-habit-rose',
  ],
  plugins: [],
};
