/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1020px',
      xl: '1200px',
      '2xl': '1720px',
      '3xl': '2500px',
    },
    extend: {
      fontFamily: {
        editorial: ['editorial'],
        'editorial-italic': ['editorial-italic'],
        montreal: ['montreal'],
      },
      colors: {
        charcoal: '#292A2D',
        parchment: '#DAD5CB',
        whisper: '#EEEFF0',
        eggshell: '#F5F4F0',
        ivory: '#FBFBF9',
        seafoam: '#A9D8C8',
        off: '#9B9B9B',
        'habit-1': '#D9D9FF',
        'habit-2': '#E6FFD9',
        'habit-3': '#BFB8FF',
        'habit-4': '#D9FFED',
        'habit-5': '#FFD9FA',
        'habit-6': '#D9F2FF',
        'habit-7': '#BBDBFF',
        'habit-8': '#FFBBDE',
        'habit-9': '#FFC9CA',
        'habit-10': '#FFFBCE',
        'habit-11': '#CEFFD0',
        'habit-12': '#FFD6B1',
      },
    },
  },
  safelist: [
    'bg-habit-1',
    'bg-habit-2',
    'bg-habit-3',
    'bg-habit-4',
    'bg-habit-5',
    'bg-habit-6',
    'bg-habit-7',
    'bg-habit-8',
    'bg-habit-9',
    'bg-habit-10',
    'bg-habit-11',
    'bg-habit-12',
  ],
  plugins: [],
};
