/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1020px',
      xl: '1200px',
      '2xl': '1720px',
      '3xl': '2500px',
    },
    extend: {
      fontFamily: {
        editorial: ['editorial'],
        'editorial-italic': ['editorial-italic'],
        montreal: ['montreal'],
      },
      colors: {
        charcoal: '#292A2D',
        parchment: '#DAD5CB',
        whisper: '#EEEFF0',
        eggshell: '#F5F4F0',
        ivory: '#FBFBF9',
        seafoam: '#A9D8C8',
        off: '#9B9B9B',
        'habit-purple': '#D9D9FF',
        'habit-green': '#E6FFD9',
        'habit-red': '#ff5a5f',
        'habit-orange': '#ffba08',
        'habit-yellow': '#ffd97d',
        'habit-light-yellow': '#fff3b0',
        'habit-lime': '#ccff33',
        'habit-light-lime': '#b2ff9e',
        'habit-mint': '#b7e4c7',
        'habit-light-mint': '#A9D8C8',
        'habit-teal': '#00b4d8',
        'habit-light-cyan': '#72efdd',
        'habit-indigo': '#BBB2E5',
        'habit-light-indigo': '#f5e6e8',
        'habit-violet': '#D5B2E5',
        'habit-pink': '#ff87ab',
        'habit-light-pink': '#ffc4d6',
        'habit-rose': '#ff758f',
      },
    },
  },
  safelist: [
    'bg-habit-purple',
    'bg-habit-green',
    'bg-habit-red',
    'bg-habit-orange',
    'bg-habit-yellow',
    'bg-habit-light-yellow',
    'bg-habit-lime',
    'bg-habit-light-lime',
    'bg-habit-mint',
    'bg-habit-light-mint',
    'bg-habit-teal',
    'bg-habit-light-cyan',
    'bg-habit-indigo',
    'bg-habit-light-indigo',
    'bg-habit-violet',
    'bg-habit-pink',
    'bg-habit-light-pink',
    'bg-habit-rose',
  ],
  plugins: [],
};
